name: Deploy Frontend Ev2F to AWS

on:
  push:
    branches:
      - deploy

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compilar y subir Imagen de Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tienda-frontendEv2F:latest

  deploy-to-aws:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar en Instancia EC2 Pública (Frontend)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/tienda-frontendEv2F:latest
            sudo docker stop tienda_frontEv2F || true
            sudo docker rm tienda_frontEv2F || true
            sudo docker run -d \
              --name tienda_frontEv2F \
              -p 80:80 \
              --restart always \
              ${{ secrets.DOCKERHUB_USERNAME }}/tienda-frontendEv2F:latest